"use client";
import { useEffect, useRef, useState } from "react";
import Modal from "@/components/ui/Modal";
import { activities as seedActivities, meeting, project } from "@/data/mockData";
import { joinClasses, priorityClasses } from "@/lib/helpers";
import { getProjectPermissions, getSelectedMember } from "@/lib/projectAccess";
import { calculateProgress, generateProjectResponse, getDocumentReview, getProjectActivities, getProjectTasks, getSessionConversation, saveConversation, saveDocumentReview, saveProjectActivities, saveProjectTasks } from "@/lib/projectState";
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-zinc-900";
const secondary="rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium hover:bg-slate-50 dark:border-white/10 dark:hover:bg-white/5";
const quick=["Summarize today's progress","What should we do next?","What risks need attention?"];
export default function DashboardClient(){
 const [member,setMember]=useState(null),[tasks,setTasks]=useState([]),[activities,setActivities]=useState(seedActivities),[review,setReview]=useState({status:"none",conflictDecision:null}),[upload,setUpload]=useState(""),[taskOpen,setTaskOpen]=useState(false),[meetingOpen,setMeetingOpen]=useState(false),[toast,setToast]=useState(""),[question,setQuestion]=useState(""),[messages,setMessages]=useState([]),[loading,setLoading]=useState(false); const end=useRef(null),submitting=useRef(false);
 useEffect(()=>{const selected=getSelectedMember();setMember(selected);setTasks(getProjectTasks(project.id));setActivities(getProjectActivities(project.id));setReview(getDocumentReview(project.id));setMessages(getSessionConversation(project.id,selected?.id))},[]);
 useEffect(()=>end.current?.scrollIntoView({behavior:"smooth",block:"nearest"}),[messages,loading]);
 const permissions=getProjectPermissions(member?.role),mine=tasks.filter(t=>t.assignee===member?.name),myProgress=calculateProgress(tasks,member?.name),overall=calculateProgress(tasks);
 const notify=m=>{setToast(m);window.setTimeout(()=>setToast(""),2400)};
 const persist=next=>{setTasks(next);saveProjectTasks(project.id,next)};
 const log=(title,meta)=>{const next=[[title,meta],...activities].slice(0,12);setActivities(next);saveProjectActivities(project.id,next)};
 function toggleTask(index){const task=tasks[index];if(!permissions.updateAnyTask&&task.assignee!==member?.name)return;const done=task.status!=="Completed",now=new Date().toISOString();persist(tasks.map((t,i)=>i===index?{...t,status:done?"Completed":"In Progress",progress:done?100:Math.min(t.progress||0,95),completedAt:done?now:null,updatedAt:now}:t));log(done?"Task completed":"Task reopened",`${task.title} · ${member.name}`);notify(done?"Task completed and saved.":"Task reopened and saved.")}
 function addTask(e){e.preventDefault();const f=new FormData(e.currentTarget),now=new Date().toISOString(),title=f.get("title");persist([...tasks,{id:`task-${Date.now()}`,title,description:f.get("description"),assignee:member?.name||"Unassigned",initials:member?.initials||"—",priority:f.get("priority"),status:"Not Started",due:"31 Jul",progress:0,updatedAt:now,completedAt:null}]);log("Task created",`${title} · just now`);setTaskOpen(false);notify("Task created.")}
 function send(prompt=question){const text=prompt.trim();if(!text||submitting.current||!permissions.askAI)return;submitting.current=true;const pending=[...messages,{id:`u-${Date.now()}`,role:"user",text}];setMessages(pending);saveConversation(project.id,member?.id,pending);setQuestion("");setLoading(true);window.setTimeout(()=>{const answer=generateProjectResponse(text,{tasks,member,meeting,activities,review,project}),next=[...pending,{id:`a-${Date.now()}`,role:"assistant",text:answer}];setMessages(next);saveConversation(project.id,member?.id,next);setLoading(false);submitting.current=false},450)}
 function keyDown(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}
 function decide(conflictDecision){const next={...review,status:"pending",conflictDecision};setReview(next);saveDocumentReview(project.id,next);notify(`${conflictDecision} saved.`)}
 function accept(){if(!review.conflictDecision){notify("Choose a deadline conflict decision first.");return}const now=new Date().toISOString(),due=review.conflictDecision==="Accept New"?"26 Jul":"24 Jul",added=[{id:"document-task-1",title:"Validate Uploaded Research Notes",description:"Review evidence detected in the latest document.",assignee:"Cynthia",initials:"CY",priority:"High",status:"Not Started",due,progress:0,updatedAt:now,completedAt:null},{id:"document-task-2",title:"Update Meeting Action Summary",description:"Apply accepted actions from the latest document.",assignee:"Darren Tin",initials:"DT",priority:"Medium",status:"Not Started",due:"27 Jul",progress:0,updatedAt:now,completedAt:null}];persist([...tasks.filter(t=>!t.id?.startsWith("document-task-")),...added]);const next={status:"accepted",conflictDecision:review.conflictDecision,acceptedAt:now,rejectedAt:null};setReview(next);saveDocumentReview(project.id,next);log("Document changes accepted",`2 tasks saved · ${review.conflictDecision}`);setUpload("");notify("Reviewed changes saved permanently.")}
 function reject(){const next={status:"rejected",conflictDecision:review.conflictDecision,acceptedAt:null,rejectedAt:new Date().toISOString()};setReview(next);saveDocumentReview(project.id,next);log("Document changes rejected","Project data was not modified");setUpload("");notify("Changes rejected. Project data was not modified.")}
 function gmail(task){const subject=`Task reminder: ${task.title}`,body=`Hi ${task.assignee},\n\nProject: ${project.name}\nTask: ${task.title}\nDeadline: ${task.due}\nProgress: ${task.progress}%\n\nPlease review and update your progress.`;window.open(`https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,"_blank","noopener,noreferrer");notify("Gmail draft opened.")}
 const calendar=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(meeting.title)}&dates=20260724T020000Z/20260724T030000Z&details=${encodeURIComponent(meeting.summary)}&location=${encodeURIComponent(meeting.location)}`;
 return <main className="mx-auto max-w-[1400px] p-4 md:p-6"><section><span className="text-[10px] font-bold tracking-widest text-blue-600">WELCOME BACK, {member?.name?.toUpperCase()||"TEAM MEMBER"}</span><h1 className="mt-1 text-2xl font-bold">Your Dashboard</h1><p className="mt-1 text-xs text-slate-500">{member?.role} · Personal view for {project.name}</p></section>
 <section className="mt-5 grid gap-4 lg:grid-cols-2"><article className={card}><span className="text-[10px] font-bold tracking-widest text-blue-600">MY PROGRESS</span><div className="mt-2 flex items-end justify-between"><div><h2 className="font-semibold">Your assigned work</h2><p className="text-xs text-slate-500">{myProgress.completed} / {myProgress.total} tasks completed</p></div><b className="text-3xl text-blue-600">{myProgress.progress}%</b></div><div className="mt-4 h-2 rounded-full bg-slate-100 dark:bg-white/10"><i style={{width:myProgress.progress+"%"}} className="block h-full rounded-full bg-blue-600"/></div><p className="mt-4 rounded-xl bg-blue-50 p-3 text-xs dark:bg-blue-500/10">Overall project progress: <b>{overall.progress}%</b> across {overall.total} tasks.</p></article><article className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-bold tracking-widest text-blue-600">YOUR NEXT ACTIONS</span><h2 className="mt-1 font-semibold">Stay focused</h2></div><div className="flex gap-2"><button onClick={()=>setMeetingOpen(true)} className={secondary}>Meeting Details</button>{permissions.uploadDocuments&&<button onClick={()=>setUpload("select")} className={secondary}>↑ Upload Document</button>}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3 dark:bg-zinc-950"><b className="text-xs">Highest priority</b><p className="mt-1 text-[10px] text-slate-500">Ask Copilot for a live recommendation.</p></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-zinc-950"><b className="text-xs">Document review</b><p className="mt-1 text-[10px] capitalize text-slate-500">Latest decision: {review.status}</p></div></div></article></section>
 <section className="mt-4 grid items-start gap-4 xl:grid-cols-[minmax(0,64fr)_minmax(340px,36fr)]"><article id="tasks" className={card}><div className="flex justify-between gap-3"><div><span className="text-[10px] font-bold tracking-widest text-blue-600">MY TASKS</span><h2 className="mt-1 font-semibold">Assigned to You</h2></div>{permissions.createTask&&<button onClick={()=>setTaskOpen(true)} className="h-fit rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white">+ Create Task</button>}</div>{mine.length?<div className="mt-4 divide-y divide-slate-100 dark:divide-white/10">{mine.map(task=>{const index=tasks.indexOf(task);return <div key={task.id||task.title} className="grid gap-3 py-4 sm:grid-cols-[1.3fr_.45fr_.7fr_.4fr_auto] sm:items-center"><div className="flex gap-3"><button onClick={()=>toggleTask(index)} aria-label={`${task.status==="Completed"?"Reopen":"Complete"} ${task.title}`} className={joinClasses("size-5 rounded-md border text-[10px]",task.status==="Completed"?"border-blue-600 bg-blue-600 text-white":"border-slate-300 text-transparent")}>✓</button><div><b className={joinClasses("block text-sm",task.status==="Completed"&&"line-through text-slate-400")}>{task.title}</b>{task.updatedAt&&<span className="text-[9px] text-slate-400">Saved {new Date(task.updatedAt).toLocaleString()}</span>}</div></div><span className="text-xs text-slate-500">{task.due}</span><div><div className="flex justify-between text-[10px] text-slate-500"><span>Progress</span><span>{task.progress}%</span></div><div className="mt-1 h-1 bg-slate-100 dark:bg-white/10"><i style={{width:task.progress+"%"}} className="block h-full bg-blue-600"/></div></div><span className={joinClasses("w-fit rounded-full px-2 py-1 text-[9px]",priorityClasses(task.priority))}>{task.priority}</span>{["Leader","Vice Leader"].includes(member?.role)&&<button onClick={()=>gmail(task)} className={secondary}>Gmail Reminder</button>}</div>})}</div>:<p className="mt-4 text-xs text-slate-500">No tasks assigned to you.</p>}</article>
 <aside id="copilot" className="sticky top-20 overflow-hidden rounded-2xl border border-violet-200 bg-white shadow-lg dark:border-violet-500/20 dark:bg-zinc-900"><header className="bg-gradient-to-r from-violet-50 to-blue-50 p-4 dark:from-violet-500/10 dark:to-blue-500/10"><b className="text-sm">✦ Project Copilot</b><span className="ml-2 text-[10px] text-slate-500">Live project context · {overall.progress}%</span></header><div className="p-4"><div className="flex flex-wrap gap-2">{quick.map(p=><button disabled={loading} key={p} onClick={()=>send(p)} className="rounded-full border border-violet-200 px-3 py-1.5 text-[10px] text-violet-700 disabled:opacity-50 dark:border-violet-500/20 dark:text-violet-300">{p}</button>)}</div><div aria-live="polite" className="mt-4 max-h-80 space-y-3 overflow-y-auto">{!messages.length&&<p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-zinc-950">Ask about tasks, members, progress, meetings, deadlines, documents, or risks.</p>}{messages.map(m=><div key={m.id} className={joinClasses("max-w-[90%] rounded-xl p-3 text-xs leading-5",m.role==="user"?"ml-auto bg-blue-600 text-white":"bg-violet-50 dark:bg-violet-500/10")}><span className="mb-1 block text-[9px] font-bold opacity-60">{m.role==="user"?"YOU":"COPILOT"}</span>{m.text}</div>)}{loading&&<div className="w-fit rounded-xl bg-violet-50 p-3 text-xs text-violet-600 dark:bg-violet-500/10">✦ Analyzing current project data…</div>}<div ref={end}/></div><div className="mt-4 flex rounded-xl border border-slate-200 p-2 dark:border-white/10"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={keyDown} rows="2" placeholder="Ask about this project..." className="min-w-0 flex-1 resize-none bg-transparent p-1 text-xs outline-none"/><button aria-label="Send message" disabled={loading||!question.trim()} onClick={()=>send()} className="size-8 rounded-lg bg-blue-600 text-white disabled:opacity-40">↑</button></div><p className="mt-2 text-[9px] text-slate-400">Enter to send · Shift + Enter for a new line</p></div></aside></section>
 {toast&&<div role="status" className="fixed right-5 top-20 z-50 rounded-xl bg-slate-950 px-4 py-3 text-xs text-white">✓ {toast}</div>}
 {meetingOpen&&<Modal title="Meeting Details" description="Review the meeting or add it to your calendar." onClose={()=>setMeetingOpen(false)}><div className="space-y-4 p-6"><div><b>{meeting.title}</b><p className="text-xs text-slate-500">{meeting.date} · {meeting.time}</p><p className="text-xs text-slate-500">{meeting.location}</p></div><p className="text-xs leading-5 text-slate-500">{meeting.summary}</p><div className="flex justify-end gap-2"><button onClick={()=>setMeetingOpen(false)} className={secondary}>Close</button><a href={calendar} target="_blank" rel="noreferrer" onClick={()=>notify("Google Calendar opened.")} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white">Add to Google Calendar</a></div></div></Modal>}
 {upload&&<Modal title="Upload Project Document" description="Review every detected change before project data is updated." onClose={()=>setUpload("")}>{upload==="select"&&<div className="p-6"><button onClick={()=>setUpload("analysis")} className="flex h-44 w-full flex-col items-center justify-center rounded-xl border border-dashed border-blue-300 bg-blue-50/50 dark:bg-blue-500/5"><b>Choose a project document</b><span className="mt-1 text-xs text-slate-500">DOCX, PDF, PPTX, XLSX or TXT</span></button><button onClick={()=>setUpload("analysis")} className="mt-4 w-full rounded-lg bg-blue-600 p-2 text-xs font-semibold text-white">Analyze Document</button></div>}{upload==="analysis"&&<div className="p-6 text-center"><h3 className="font-semibold">Analyzing project changes</h3><p className="mt-2 text-xs text-slate-500">Nothing changes until you review and accept it.</p><button onClick={()=>{const next={...review,status:"pending"};setReview(next);saveDocumentReview(project.id,next);setUpload("review")}} className="mt-5 rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white">View Detected Changes</button></div>}{upload==="review"&&<div className="space-y-4 p-6"><div><span className="text-[10px] font-bold text-blue-600">DETECTED CHANGES</span><h3 className="font-semibold">+2 Tasks · Meeting Updated · Deadline Changed</h3></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:bg-amber-500/10"><b className="text-xs">Deadline conflict</b><div className="mt-3 flex justify-between text-xs"><span>Existing: 24 Jul</span><span>New: 26 Jul</span></div><div className="mt-3 flex gap-2">{["Keep Existing","Accept New"].map(d=><button key={d} onClick={()=>decide(d)} className={joinClasses(secondary,review.conflictDecision===d&&"border-blue-600 bg-blue-50 text-blue-700")}>{d}</button>)}</div></div><div className="flex justify-end gap-2"><button onClick={reject} className={secondary}>Reject Changes</button><button onClick={accept} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white">Accept Changes</button></div></div>}</Modal>}
 {taskOpen&&<Modal title="Create a task" description="Add actionable work to the project." onClose={()=>setTaskOpen(false)}><form onSubmit={addTask} className="space-y-4 p-6"><label className="block text-sm">Title<input name="title" required className="mt-2 w-full rounded-lg border p-3 dark:border-white/10 dark:bg-transparent"/></label><label className="block text-sm">Description<textarea name="description" className="mt-2 w-full rounded-lg border p-3 dark:border-white/10 dark:bg-transparent"/></label><label className="block text-sm">Priority<select name="priority" className="mt-2 w-full rounded-lg border p-3 dark:border-white/10 dark:bg-transparent"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setTaskOpen(false)} className={secondary}>Cancel</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-xs text-white">Create Task</button></div></form></Modal>}
 </main>}
